version: '2'

services:
  scheduler:
    image: registry.nodeart.io/rss/radio-scheduler:latest
    build: ./bin/release/netcoreapp1.1/publish/radio-scheduler
    networks:
      - test-net
    volumes:
       - ./volumes/task:/data/task

  listener:
    image: registry.nodeart.io/rss/radio-listener:latest
    build: ./bin/release/netcoreapp1.1/publish/radio-listener
    depends_on: 
      - scheduler
    networks:
      - test-net
    volumes:
      - ./volumes/audio:/data/audio

  identification:
    image: registry.nodeart.io/rss/radio-identification:latest
    build: ./bin/release/netcoreapp1.1/publish/radio-listener
    networks: 
      - test-net
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/data/credentials/radio-monitoring.json
    volumes:
      - ./volumes/credentials:/data/credentials
      - ./volumes/audio:/data/audio

  manager-server:
    image: registry.nodeart.io/rss/manager-server:latest
    build: ./bin/release/netcoreapp1.1/publish/manager-server
    ports:
      - "80:80"
    networks: 
      - test-net

  storage-server:
    image: storage-server
    build: ./bin/release/netcoreapp1.1/publish/storage-server
    networks: 
      - test-net

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - test-net

networks:
   test-net: