version: '2'

services:
  listener:
    image: listener:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    networks:
      - test-net
    environment:
      - REMOTE_DEBUGGING
    volumes: 
       - ./volumes/audio:/data/audio

networks:
   test-net: