#!/bin/sh

if [ -z "$1" ]
  then
    echo "No stream supplied"
    exit 1
fi

STREAM=$1
echo $STREAM

# mkdir -p records

# streamripper $STREAM -l $DURATION -d $(pwd)/records -a test -o always
# panako client "$SERVER:$PORT" records/test.mp3

# rm -rf records