version: '2'

services:
  scheduler:
    image: scheduler:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    networks:
      - test-net
    environment:
      - REMOTE_DEBUGGING
    volumes:
       - ./volumes/task:/data/task

networks:
   test-net: